export const FETCHING_LATEST_RATES = "FETCHING_LATEST_RATES";
export const FETCHING_LATEST_RATES_SUCCESS = "FETCHING_LATEST_RATES_SUCCESS";
export const FETCHING_LATEST_RATES_FAILURE = "FETCHING_LATEST_RATES_FAILURE";